**Numpy**

Array


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr=np.array([[1,2],[4,5]])
arr1=np.array([[[1,2],[4,5]]])
print(arr)
print(type(arr))
print("Dimension: ",arr.ndim)
print(arr1)
print(type(arr1))
print("Dimension: ",arr1.ndim)
a5=np.array([1,2,3,4],ndmin=5)
print(a5)
print("Dimension: ",a5.ndim)

[[1 2]
 [4 5]]
<class 'numpy.ndarray'>
Dimension:  2
[[[1 2]
  [4 5]]]
<class 'numpy.ndarray'>
Dimension:  3
[[[[[1 2 3 4]]]]]
Dimension:  5


In [ ]:
arr1=np.array([[[1,2],[4,5]],[[5,6],[7,8]]])
print(arr1[0,0], arr1[1,0])

[1 2] [5 6]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,0::2],arr[1,0::2])

[1 3 5] [ 6  8 10]


In [ ]:
b=[1,2,3,4,5,6,7,8,9,10]
print(b[-10::-2])

[1]


In [ ]:
b=[1,2,3,4]
print(b[::2])

[1, 3]


In [ ]:
b=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(b[0,0::3],b[1,0::3])

[1 2 3 4 5] [11 12 13 14 15]


**Copy,View,Shape and Reshape**

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr.shape)
print(arr)
newarr=arr.reshape(5,3)
print(newarr)
arr1=arr.reshape(3,5)
print(arr1)
arr2=arr.reshape(2,3)
print(arr2)
arr3=arr.reshape(3,2)
print(arr3)

(15,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


ValueError: cannot reshape array of size 15 into shape (2,3)

In [ ]:
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3)
print(newarr)
arr1=newarr.reshape(-1)
print(arr1)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
arr1=np.ones(5)
print(arr1)
arr2=np.arange(1,5)
print(arr2)
print(arr2.dtype)
arr=np.zeros(5,dtype='S')
print(arr.dtype)

[1. 1. 1. 1. 1.]
[1 2 3 4]
int64
|S1


In [ ]:
arr=np.array([1,2,3,4,5,6])

arr1=np.sum(arr)
print(arr1)
arr1=np.mean(arr)
print(arr1)
arr1=np.median(arr)
print(arr1)


21
3.5
3.5


In [ ]:
a=[10,20,30,40]
a+=5
print(a)

TypeError: 'int' object is not iterable